// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Concluded   bool
	ExpiresAt   sql.NullTime
	Priority    string
	IsDaily     bool
}
