// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos_history.sql

package database

import (
	"context"
	"database/sql"
)

const addDailyTaskHistory = `-- name: AddDailyTaskHistory :one
INSERT INTO todos_history (id, todo_id, date, completed, completed_at, notes)
VALUES (
    ?, ?, date('now', 'localtime'), ?, ?, ?
) 
ON CONFLICT(todo_id, date) DO NOTHING
RETURNING id, todo_id, date, completed, completed_at, notes
`

type AddDailyTaskHistoryParams struct {
	ID          interface{}
	TodoID      interface{}
	Completed   sql.NullBool
	CompletedAt sql.NullTime
	Notes       sql.NullString
}

func (q *Queries) AddDailyTaskHistory(ctx context.Context, arg AddDailyTaskHistoryParams) (TodosHistory, error) {
	row := q.db.QueryRowContext(ctx, addDailyTaskHistory,
		arg.ID,
		arg.TodoID,
		arg.Completed,
		arg.CompletedAt,
		arg.Notes,
	)
	var i TodosHistory
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.Notes,
	)
	return i, err
}

const addDailyTaskHistoryForDate = `-- name: AddDailyTaskHistoryForDate :one
INSERT INTO todos_history (id, todo_id, date, completed, completed_at, notes)
VALUES (
    ?, ?, date(?), ?, ?, ?
) 
ON CONFLICT(todo_id, date) DO NOTHING
RETURNING id, todo_id, date, completed, completed_at, notes
`

type AddDailyTaskHistoryForDateParams struct {
	ID          interface{}
	TodoID      interface{}
	Date        interface{}
	Completed   sql.NullBool
	CompletedAt sql.NullTime
	Notes       sql.NullString
}

func (q *Queries) AddDailyTaskHistoryForDate(ctx context.Context, arg AddDailyTaskHistoryForDateParams) (TodosHistory, error) {
	row := q.db.QueryRowContext(ctx, addDailyTaskHistoryForDate,
		arg.ID,
		arg.TodoID,
		arg.Date,
		arg.Completed,
		arg.CompletedAt,
		arg.Notes,
	)
	var i TodosHistory
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.Notes,
	)
	return i, err
}

const addTodoHistory = `-- name: AddTodoHistory :one
INSERT INTO todos_history (id, todo_id, date, completed, completed_at, notes)
VALUES (
    ?, ?, date('now', 'localtime'), ?, ?, ?
) 
ON CONFLICT(todo_id, date) DO UPDATE SET
    completed = excluded.completed,
    completed_at = excluded.completed_at,
    notes = excluded.notes
RETURNING id, todo_id, date, completed, completed_at, notes
`

type AddTodoHistoryParams struct {
	ID          interface{}
	TodoID      interface{}
	Completed   sql.NullBool
	CompletedAt sql.NullTime
	Notes       sql.NullString
}

func (q *Queries) AddTodoHistory(ctx context.Context, arg AddTodoHistoryParams) (TodosHistory, error) {
	row := q.db.QueryRowContext(ctx, addTodoHistory,
		arg.ID,
		arg.TodoID,
		arg.Completed,
		arg.CompletedAt,
		arg.Notes,
	)
	var i TodosHistory
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.Notes,
	)
	return i, err
}

const getCurrentStreak = `-- name: GetCurrentStreak :one
WITH ordered AS (
    SELECT
        date,
        completed,
        julianday(date) - julianday(LAG(date) OVER (ORDER BY date ASC)) AS days_diff
    FROM todos_history
    WHERE todo_id = ?
      AND date <= date('now', 'localtime')
    ORDER BY date ASC
),
grouped AS (
    SELECT
        date,
        completed,
        SUM(
            CASE
                WHEN completed = 0 THEN 1
                WHEN days_diff > 1 THEN 1
                ELSE 0
            END
        ) OVER (ORDER BY date ASC ROWS UNBOUNDED PRECEDING) AS streak_group
    FROM ordered
),
current_group AS (
    SELECT streak_group
    FROM grouped
    ORDER BY date DESC
    LIMIT 1
)
SELECT COUNT(*) AS current_streak
FROM grouped
WHERE completed = 1
  AND streak_group = (SELECT streak_group FROM current_group)
`

// Returns the number of consecutive completed days ending on the most recent entry.
// Fix: uses ASC ordering for LAG so days_diff is always positive for consecutive days,
// and anchors the current group on the latest entry instead of requiring today's date
// to exist in the table (so the streak is not broken mid-day before the cron runs).
func (q *Queries) GetCurrentStreak(ctx context.Context, todoID interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentStreak, todoID)
	var current_streak int64
	err := row.Scan(&current_streak)
	return current_streak, err
}

const getStreakHistory = `-- name: GetStreakHistory :many
WITH ordered AS (
    SELECT
        date,
        completed,
        julianday(date) - julianday(LAG(date) OVER (ORDER BY date ASC)) AS days_diff
    FROM todos_history
    WHERE todo_id = ?
    ORDER BY date ASC
),
grouped AS (
    SELECT
        date,
        completed,
        SUM(
            CASE
                WHEN completed = 0 THEN 1
                WHEN days_diff > 1 THEN 1
                ELSE 0
            END
        ) OVER (ORDER BY date ASC ROWS UNBOUNDED PRECEDING) AS streak_id
    FROM ordered
),
streaks AS (
    SELECT
        streak_id,
        MIN(date) AS start_date,
        MAX(date) AS end_date,
        COUNT(*)  AS streak_length
    FROM grouped
    WHERE completed = 1
    GROUP BY streak_id
)
SELECT
    start_date,
    end_date,
    streak_length
FROM streaks
ORDER BY streak_length DESC, start_date DESC
`

type GetStreakHistoryRow struct {
	StartDate    interface{}
	EndDate      interface{}
	StreakLength int64
}

// Returns all completed streak intervals ordered by length descending.
// Fix: removed HAVING days_count = streak_length which silently dropped any streak
// with an internal gap, and removed streak_length > 1 so single-day streaks appear.
func (q *Queries) GetStreakHistory(ctx context.Context, todoID interface{}) ([]GetStreakHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getStreakHistory, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStreakHistoryRow
	for rows.Next() {
		var i GetStreakHistoryRow
		if err := rows.Scan(&i.StartDate, &i.EndDate, &i.StreakLength); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
