// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos_history.sql

package database

import (
	"context"
	"database/sql"
)

const addTodoHistory = `-- name: AddTodoHistory :one
INSERT INTO todos_history (id, todo_id, date, completed, completed_at, notes)
VALUES (
  ?, ?, ?, ?, ?, ?
) RETURNING id, todo_id, date, completed, completed_at, notes
`

type AddTodoHistoryParams struct {
	ID          interface{}
	TodoID      interface{}
	Date        sql.NullTime
	Completed   sql.NullBool
	CompletedAt sql.NullTime
	Notes       sql.NullString
}

func (q *Queries) AddTodoHistory(ctx context.Context, arg AddTodoHistoryParams) (TodosHistory, error) {
	row := q.db.QueryRowContext(ctx, addTodoHistory,
		arg.ID,
		arg.TodoID,
		arg.Date,
		arg.Completed,
		arg.CompletedAt,
		arg.Notes,
	)
	var i TodosHistory
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.Notes,
	)
	return i, err
}
