// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos_history.sql

package database

import (
	"context"
	"database/sql"
)

const addDailyTaskHistory = `-- name: AddDailyTaskHistory :one
INSERT INTO todos_history (id, todo_id, date, completed, completed_at, notes)
VALUES (
  ?, ?, date('now'), ?, ?, ?
) 
ON CONFLICT(todo_id, date) DO NOTHING
RETURNING id, todo_id, date, completed, completed_at, notes
`

type AddDailyTaskHistoryParams struct {
	ID          interface{}
	TodoID      interface{}
	Completed   sql.NullBool
	CompletedAt sql.NullTime
	Notes       sql.NullString
}

func (q *Queries) AddDailyTaskHistory(ctx context.Context, arg AddDailyTaskHistoryParams) (TodosHistory, error) {
	row := q.db.QueryRowContext(ctx, addDailyTaskHistory,
		arg.ID,
		arg.TodoID,
		arg.Completed,
		arg.CompletedAt,
		arg.Notes,
	)
	var i TodosHistory
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.Notes,
	)
	return i, err
}

const addTodoHistory = `-- name: AddTodoHistory :one
INSERT INTO todos_history (id, todo_id, date, completed, completed_at, notes)
VALUES (
  ?, ?, ?, ?, ?, ?
) RETURNING id, todo_id, date, completed, completed_at, notes
`

type AddTodoHistoryParams struct {
	ID          interface{}
	TodoID      interface{}
	Date        sql.NullTime
	Completed   sql.NullBool
	CompletedAt sql.NullTime
	Notes       sql.NullString
}

func (q *Queries) AddTodoHistory(ctx context.Context, arg AddTodoHistoryParams) (TodosHistory, error) {
	row := q.db.QueryRowContext(ctx, addTodoHistory,
		arg.ID,
		arg.TodoID,
		arg.Date,
		arg.Completed,
		arg.CompletedAt,
		arg.Notes,
	)
	var i TodosHistory
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Date,
		&i.Completed,
		&i.CompletedAt,
		&i.Notes,
	)
	return i, err
}

const getCurrentStreak = `-- name: GetCurrentStreak :one
WITH daily_completions AS (
    SELECT 
        date,
        completed,
        date as ref_date, 
        julianday(date) - julianday(LAG(date) OVER (ORDER BY date DESC)) as days_diff
    FROM todos_history
    WHERE todo_id = ?
    ORDER BY date DESC
    LIMIT 100
),
streak_calc AS (
    SELECT 
        date,
        completed,
        days_diff,
        CASE 
            WHEN completed = 0 THEN 0 
            WHEN days_diff > 1 THEN 0
            ELSE 1
        END as is_streak_day,
        SUM(CASE 
            WHEN completed = 0 OR days_diff > 1 THEN 1 
            ELSE 0 
        END) OVER (ORDER BY date DESC ROWS UNBOUNDED PRECEDING) as streak_group
    FROM daily_completions
    WHERE date <= date('now')
)
SELECT 
    COUNT(*) as current_streak
FROM streak_calc
WHERE 
    completed = 1 
    AND streak_group = (
        SELECT streak_group 
        FROM streak_calc 
        WHERE date = date('now')
        LIMIT 1
    )
AND date <= date('now')
`

func (q *Queries) GetCurrentStreak(ctx context.Context, todoID interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentStreak, todoID)
	var current_streak int64
	err := row.Scan(&current_streak)
	return current_streak, err
}

const getStreakHistory = `-- name: GetStreakHistory :many
WITH streak_groups AS (
    SELECT 
        date,
        completed,
        SUM(CASE 
            WHEN completed = 0 OR 
                 julianday(date) - julianday(LAG(date) OVER (ORDER BY date)) > 1 
            THEN 1 ELSE 0 
        END) OVER (ORDER BY date) as streak_id
    FROM todos_history
    WHERE todo_id = ?
    ORDER BY date
),
streaks AS (
    SELECT 
        streak_id,
        MIN(date) as start_date,
        MAX(date) as end_date,
        COUNT(*) as streak_length,
        julianday(MAX(date)) - julianday(MIN(date)) + 1 as days_count
    FROM streak_groups
    WHERE completed = 1
    GROUP BY streak_id
    HAVING days_count = streak_length
)
SELECT 
    start_date,
    end_date,
    streak_length
FROM streaks
WHERE streak_length > 1
ORDER BY streak_length DESC, start_date DESC
`

type GetStreakHistoryRow struct {
	StartDate    interface{}
	EndDate      interface{}
	StreakLength int64
}

func (q *Queries) GetStreakHistory(ctx context.Context, todoID interface{}) ([]GetStreakHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getStreakHistory, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStreakHistoryRow
	for rows.Next() {
		var i GetStreakHistoryRow
		if err := rows.Scan(&i.StartDate, &i.EndDate, &i.StreakLength); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
