// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addTodo = `-- name: AddTodo :one
INSERT INTO todos (id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily)
VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ? 
)
RETURNING id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily
`

type AddTodoParams struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Concluded   bool
	ExpiresAt   time.Time
	Priority    string
	IsDaily     bool
}

func (q *Queries) AddTodo(ctx context.Context, arg AddTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, addTodo,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Concluded,
		arg.ExpiresAt,
		arg.Priority,
		arg.IsDaily,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Concluded,
		&i.ExpiresAt,
		&i.Priority,
		&i.IsDaily,
	)
	return i, err
}

const autoCompleteDelete = `-- name: AutoCompleteDelete :one
SELECT name FROM todos 
WHERE NAME LIKE ? || '%'
ORDER BY NAME LIMIT 5
`

func (q *Queries) AutoCompleteDelete(ctx context.Context, dollar_1 sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, autoCompleteDelete, dollar_1)
	var name string
	err := row.Scan(&name)
	return name, err
}

const checkExpired = `-- name: CheckExpired :many
SELECT id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily FROM todos 
WHERE expires_at < datetime('now') AND is_daily = false
ORDER BY expires_at DESC
`

func (q *Queries) CheckExpired(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, checkExpired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Concluded,
			&i.ExpiresAt,
			&i.Priority,
			&i.IsDaily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteConcluded = `-- name: DeleteConcluded :exec
DELETE FROM todos 
WHERE concluded = true
`

func (q *Queries) DeleteConcluded(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteConcluded)
	return err
}

const deleteTodoByName = `-- name: DeleteTodoByName :exec
DELETE FROM todos 
WHERE name LIKE ?
`

func (q *Queries) DeleteTodoByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteTodoByName, name)
	return err
}

const getDailyTodos = `-- name: GetDailyTodos :many
SELECT id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily FROM todos 
WHERE is_daily = true
`

func (q *Queries) GetDailyTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getDailyTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Concluded,
			&i.ExpiresAt,
			&i.Priority,
			&i.IsDaily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIDByName = `-- name: GetIDByName :one
SELECT id FROM todos 
WHERE name = ?
`

func (q *Queries) GetIDByName(ctx context.Context, name string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getIDByName, name)
	var id interface{}
	err := row.Scan(&id)
	return id, err
}

const getTodoByName = `-- name: GetTodoByName :one
WITH ranked_todos AS (
  SELECT id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily,
    CASE
    -- same text 
    WHEN LOWER(name) = LOWER(?) THEN 1
    -- begins with the term 
    WHEN LOWER(name) LIKE LOWER(?) || '%' THEN 2
    WHEN LOWER(name) LIKE '%' || LOWER(?) || '%' THEN 3
    ELSE 4 
    END as relevance
  FROM todos
  WHERE LOWER(name) LIKE '%' || LOWER(?) || '%'
) 
SELECT id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily, relevance FROM ranked_todos
ORDER BY relevance, name COLLATE NOCASE
LIMIT 1
`

type GetTodoByNameParams struct {
	LOWER   string
	LOWER_2 string
	LOWER_3 string
	LOWER_4 string
}

type GetTodoByNameRow struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Concluded   bool
	ExpiresAt   time.Time
	Priority    string
	IsDaily     bool
	Relevance   int64
}

func (q *Queries) GetTodoByName(ctx context.Context, arg GetTodoByNameParams) (GetTodoByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getTodoByName,
		arg.LOWER,
		arg.LOWER_2,
		arg.LOWER_3,
		arg.LOWER_4,
	)
	var i GetTodoByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Concluded,
		&i.ExpiresAt,
		&i.Priority,
		&i.IsDaily,
		&i.Relevance,
	)
	return i, err
}

const getTodos = `-- name: GetTodos :many
SELECT id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily FROM todos
ORDER BY expires_at
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Concluded,
			&i.ExpiresAt,
			&i.Priority,
			&i.IsDaily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDailyTodo = `-- name: UpdateDailyTodo :many
UPDATE todos 
SET 
  expires_at = ?, 
  updated_at = CURRENT_TIMESTAMP, 
  concluded = false 
WHERE 
  is_daily = true 
  AND expires_at < datetime('now', 'start of day', 'localtime')
RETURNING id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily
`

func (q *Queries) UpdateDailyTodo(ctx context.Context, expiresAt time.Time) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, updateDailyTodo, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Concluded,
			&i.ExpiresAt,
			&i.Priority,
			&i.IsDaily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoStatusByName = `-- name: UpdateTodoStatusByName :one
UPDATE todos 
SET concluded = true, updated_at = datetime('now')
WHERE name LIKE ?
RETURNING id, name, description, created_at, updated_at, concluded, expires_at, priority, is_daily
`

func (q *Queries) UpdateTodoStatusByName(ctx context.Context, name string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoStatusByName, name)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Concluded,
		&i.ExpiresAt,
		&i.Priority,
		&i.IsDaily,
	)
	return i, err
}
