// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addTodo = `-- name: AddTodo :one
INSERT INTO todos (id, name, description, created_at, updated_at, concluded, expires_at)
VALUES (
  ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, description, created_at, updated_at, concluded, expires_at
`

type AddTodoParams struct {
	ID          interface{}
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Concluded   bool
	ExpiresAt   sql.NullTime
}

func (q *Queries) AddTodo(ctx context.Context, arg AddTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, addTodo,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Concluded,
		arg.ExpiresAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Concluded,
		&i.ExpiresAt,
	)
	return i, err
}

const checkExpired = `-- name: CheckExpired :many
SELECT id, name, description, created_at, updated_at, concluded, expires_at FROM todos 
WHERE expires_at < datetime('now')
ORDER BY expires_at DESC
`

func (q *Queries) CheckExpired(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, checkExpired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Concluded,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteConcluded = `-- name: DeleteConcluded :exec
DELETE FROM todos 
WHERE concluded = true
`

func (q *Queries) DeleteConcluded(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteConcluded)
	return err
}

const deleteTodoByName = `-- name: DeleteTodoByName :exec
DELETE FROM todos 
WHERE name LIKE ?
`

func (q *Queries) DeleteTodoByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteTodoByName, name)
	return err
}

const getTodoByName = `-- name: GetTodoByName :one
SELECT id, name, description, created_at, updated_at, concluded, expires_at FROM todos 
WHERE name LIKE ?
`

func (q *Queries) GetTodoByName(ctx context.Context, name string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByName, name)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Concluded,
		&i.ExpiresAt,
	)
	return i, err
}

const getTodos = `-- name: GetTodos :many
SELECT id, name, description, created_at, updated_at, concluded, expires_at FROM todos
`

func (q *Queries) GetTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Concluded,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoStatusByName = `-- name: UpdateTodoStatusByName :one
UPDATE todos 
SET concluded = true, updated_at = datetime('now')
WHERE name LIKE ?
RETURNING id, name, description, created_at, updated_at, concluded, expires_at
`

func (q *Queries) UpdateTodoStatusByName(ctx context.Context, name string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoStatusByName, name)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Concluded,
		&i.ExpiresAt,
	)
	return i, err
}
